import type { RocketConfig, RocketState, Detached } from './rocket.ts';
import type { Condition, ConditionMemory, WindowMemory } from './conditions.ts';
import type { Vec } from '../physics/vector.ts';
export type Body = {
  id: string;
  name: string;
  kind: 'star' | 'planet' | 'moon' | 'black-hole' | 'barycenter';
  position: Vec;
  radius: number;
  mu: number;
  color: string;
  dynamic?: { velocity: Vec; epoch?: number };
  atmosphere?: { height: number; density: number; scaleHeight: number };
  spin?: number;
  hiddenGravity: boolean;
  estimateMu: number;
  motion?: { parentId: string; radius: number; phase: number; angularSpeed?: number };
};
export type DeviceKind = 'speed' | 'gravity' | 'distance' | 'direction' | 'clock';
export type WorldObject = {
  id: string;
  kind: 'sensor' | 'gate' | 'hazard' | 'station' | 'path';
  name: string;
  position: Vec;
  radius: number;
  angle: number;
  points?: Vec[];
  sensor: DeviceKind;
  motion?: Body['motion'];
};
export type Goal = {
  id: string;
  title: string;
  condition: Condition;
  position: Vec;
  startTime: number;
  endTime: number;
  dependsOn: string[];
  display?: { targetId: string; min: number; max: number };
};
export type Impulse = { id: string; time: number; vector: Vec };
export type RoutePlan = {
  launch: Vec;
  impulses: Impulse[];
  engineCommands?: {
    id: string;
    time: number;
    actorId: string;
    throttle?: number;
    direction?: Vec;
    separate?: boolean;
  }[];
  deployments?: { id: string; time: number; kind: DeviceKind }[];
};
export type Stage = {
  version: 2;
  randomization?: import('./variation').VariationBank;
  published?: boolean;
  launchBodyId?: string;
  launchAngle?: number;
  rocket?: RocketConfig;
  id: string;
  title: string;
  description: string;
  order: number;
  theme: string;
  bodies: Body[];
  objects: WorldObject[];
  goals: Goal[];
  goalMode: 'all' | 'any';
  spawn: { position: Vec; velocity: Vec };
  rules: {
    surfaceClearance?: number;
    launchLimit: number;
    maneuverBudget: number;
    maxTime: number;
    worldRadius: number;
    sensorSlots: number;
    attempts: number;
  };
  camera: { x: number; y: number; zoom: number };
  referencePlans: RoutePlan[];
  audit: { samples: number; maxPassRate: number; seed: number };
};
export type GoalProgress = {
  complete: boolean;
  ratio: number;
  conditionMemory?: ConditionMemory;
  checkpoints?: Record<string, { value: number; time: number }>;
  windows?: Record<string, WindowMemory>;
};
export type Observation = {
  id: string;
  deviceId: string;
  kind: DeviceKind;
  position: Vec;
  time: number;
  value: number;
  vector: Vec;
  text: string;
};
export type Run = {
  time: number;
  position: Vec;
  velocity: Vec;
  used: number;
  status: 'running' | 'won' | 'failed' | 'observed' | 'impact' | 'aborted';
  reason: string;
  probe: boolean;
  applied: Set<string>;
  trail: { position: Vec; time: number; velocity: Vec }[];
  observations: Observation[];
  sampled: Set<string>;
  goals: Record<string, GoalProgress>;
  lastTrail: number;
  plan: RoutePlan;
  rocket?: RocketState;
  detached: Detached[];
  bodies?: Record<string, import('./dynamics.ts').BodyState>;
  landed?: { bodyId: string; angle: number };
  touchdownSpeed?: number;
  impact?: import('./impact').Impact;
  buoys: { id: string; kind: DeviceKind; position: Vec; velocity: Vec; lastSample: number }[];
};
export type GoalContext = {
  stage: Stage;
  run: Run;
  before: Vec;
  beforeActors?: Record<string, Vec>;
  dt: number;
  previousTime: number;
  collisionBodyId?: string;
  actorId?: string;
};
