import { mkdir } from 'node:fs/promises';
import { chromium } from '@playwright/test';
await mkdir('test-results/screens', { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', (error) => errors.push(error.message));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('button', { name: '탐사 시작' }).waitFor();
await page.screenshot({ path: 'test-results/screens/title.png' });
await page.getByRole('button', { name: '탐사 시작' }).click();
await page.locator('#world').waitFor();
await page.waitForTimeout(250);
await page.screenshot({ path: 'test-results/screens/play.png' });
await page.goto('http://127.0.0.1:5173/?editor=1');
await page.locator('#editor-world').waitFor();
await page.waitForTimeout(1000);
await page.screenshot({ path: 'test-results/screens/editor.png' });
console.log(JSON.stringify({ errors }));
await browser.close();
